name: Build, Test, and Push Docker Image


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1 Checkout 
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3 Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4 Build
      - name: Build the Docker image
        run: docker build . -t razbo/final-python-main:latest

  
      # Step 5 Test
      - name: Test the Docker image
        run: |
          docker run --rm razbo/final-python-main:latest pytest
          
      # Step 6 Push
      - name: Push the Docker image to DockerHub
        run: docker push razbo/final-python-main:latest
