name: Build, Test, and Push Docker Image

# Run this workflow on every push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx for building multi-platform images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build the Docker image
      - name: Build the Docker image
        run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest

      # Step 5: Run container tests
      - name: Run container tests
        run: |
          docker run --rm ${{ secrets.DOCKER_USERNAME }}/my-app:latest <your-test-command>

      # Step 6: Push the Docker image to DockerHub
      - name: Push the Docker image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest
