name: Build, Test and Push Docker Image

on:
  push:
    branches:
      - main   # Run workflow when code is pushed to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker Buildx (optional for multi-arch builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Step 4: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/final-python-main:latest .
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/final-python-main:latest ${{ secrets.DOCKERHUB_USERNAME }}/final-python-main:latest

    # Step 5: Test the Docker image
    - name: Test Docker image
      run: |
        # Example: Running a simple test
        docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/final-python-main:latest echo "Test Passed"

    # Step 6: Push Docker image to DockerHub
    - name: Push Docker image to DockerHub
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/final-python-main:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/final-python-main:latest
