name: Build and Test Containers

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and Test Containers
        run: |
          docker build -t final-python-main .
          docker run --rm final-python-main:latest /bin/sh -c "test -f tests/test.sh && ./tests/test.sh"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image to Docker Hub
        run: docker push final-python-main:latest
