name: Build, Test, and Deploy Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build . -t razbo/final-python-main:333

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test the Docker image
        run: |
          docker run --rm razbo/final-python-main:333 python --version

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push the Docker image to DockerHub
        run: docker push razbo/final-python-main:333

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3


      
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: raz-final-exem-task-revision2.json
          container-name: final-python-main
          image: razbo/final-python-main:333
  
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: final-exam-service
          cluster: raz-final-exam
          wait-for-service-stability: true


        
      # - name: Update ECS Service
      #   run: |
      #     ecs_service_name="final-exam-service"
      #     ecs_cluster_name="raz-final-exam"
      #     container_name="final-python-main"
      #     docker_image="razbo/final-python-main:333"
          
      #     aws ecs update-service \
      #       --cluster $ecs_cluster_name \
      #       --service $ecs_service_name \
      #       --task-definition raz-final-exem-task:2 \
      #       --force-new-deployment \
      #       --region eu-west-3
